apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2026-07-19T12:32:51Z"
  labels:
    app: nginx-gateway
    model: qwen-32b-gptq
  name: nginx-gateway-32b
  namespace: aither-inference
  resourceVersion: "830868"
  uid: ec7599b6-c3bb-421a-87dc-c0a6516417df
spec:
  clusterIP: 10.106.31.143
  clusterIPs:
  - 10.106.31.143
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: nginx-gateway
    model: qwen-32b-gptq
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}