apiVersion: v1
kind: Service
metadata:
  name: vllm-api
  namespace: aither-inference
  labels:
    app: vllm
spec:
  type: ClusterIP
  selector:
    app: vllm
  ports:
    - port: 8000
      targetPort: 8000
      name: openai-api-14b
    - port: 8001
      targetPort: 8001
      name: openai-api-32b
