#!/bin/bash
# transfer.sh — инструкция по переносу моделей через внешний диск
echo "=== Перенос моделей в закрытый контур ==="
echo ""
echo "ШАГ 1: На машине с интернетом скачайте модели:"
echo "  pip install huggingface_hub"
echo "  huggingface-cli download Qwen/Qwen2.5-14B-Instruct --local-dir /tmp/models/Qwen2.5-14B-Instruct"
echo "  huggingface-cli download Qwen/Qwen2.5-32B-Instruct-GPTQ --local-dir /tmp/models/Qwen2.5-32B-Instruct-GPTQ"
echo ""
echo "ШАГ 2: Скопируйте на внешний диск:"
echo "  cp -r /tmp/models /media/EXTERNAL_DRIVE/"
echo ""
echo "ШАГ 3: На целевой машине:"
echo "  cp -r /media/EXTERNAL_DRIVE/models/* /mnt/models/"
echo ""
echo "ШАГ 4: Проверьте:"
echo "  ls -la /mnt/models/Qwen2.5-14B-Instruct/"
echo "  ls -la /mnt/models/Qwen2.5-32B-Instruct-GPTQ/"
echo ""
echo "Размеры:"
echo "  Qwen2.5-14B-Instruct      ~28 GB"
echo "  Qwen2.5-32B-Instruct-GPTQ ~20 GB"
echo "  Итого:                    ~48 GB (влезает на USB-HDD 64+ GB)"
